apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-kube
  template:
    metadata:
      labels:
        app: node-kube
    spec: 
      containers:
        - name: node-kube-containor
          image: node-test:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3000