apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-kube-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-kube-deployment
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 5  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target average CPU utilization (percentage)