name: Deploy to GKE

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy-to-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-test:{{ github.run_number }} .

    - name: Tag docker image
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/node-test:{{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/node-test:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/node-test:{{ github.run_number }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: project-1-400619
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
          
    - name: Configure docker for GCP
      run: gcloud auth configure-docker gcr.io

    - name: Configure kubectl
      run: gcloud container clusters get-credentials node-cluster-demo --region us-central1 --project inspired-aria-398923
    
    - name: Apply Kubernetes files
      run: kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml
